### ISSUE TITLE
Question: Supported browsers?

### ISSUE THREAD

**Issue by steveoh** [tawian/text-spinners#7]
Would you mind adding browser support to your readme?

**Comment by maxbeier** [comment]
Jeah, to be honest, I was too lazy. But I will do it :)

**Comment by maxbeier** [comment]
Hey, I added the browsers I have access to. Would be great if you'd add more, if you can.

**Comment by steveoh** [comment]
Wouldn't the main support come from browsers that support these features?

http://caniuse.com/#feat=css-animation
http://caniuse.com/#feat=css-gencontent

**Comment by maxbeier** [comment]
I thought about it, but it's not just the feature support (and caniuse only lists the support for `animation`, but if I remember correctly, that wasn't congruent with the support for `steps`) but also a visual thing. It took some testing to find the right values that worked across browsers and I don't know why some things didn't work in one but the others; so I would want someone to see it to believe that it works :D Anyways, I think it might be just IE10 that's missing and I'll add it if I find one. The others are evergreens or their prior versions are little used today. Or am I missing a browser or version?

**Comment by ararslan** [comment]
I have access to Microsoft Edge and I can confirm that it works in Edge 25. (Not that anyone actually uses Edge... :trollface:)

**Comment by maxbeier** [comment]
Thanks, I added it.

@steveoh Is the current state ok for you? I would close the issue then.

**Comment by steveoh** [comment]
I'd like to find the support for steps. I think that including the step support with the data from caniuse would be optimal. Then you'd have a matrix for deciding if this can work for your project and it's supported browsers.

**Comment by maxbeier** [comment]
Ok, would be cool if you'd open a new issue if you find the support for `steps`. Till then I will close this issue as the general support was added to the readme.
